# Generated by Django 4.0 on 2022-01-05 07:37

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_product_img_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=product.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=product.models.path_and_rename),
        ),
    ]
