# Generated by Django 4.0 on 2022-01-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_active_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='active',
            field=models.BooleanField(choices=[(True, 'In Stock'), (False, 'Out Stock')], default=True),
        ),
    ]
