# Generated by Django 4.0 on 2022-01-05 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_category_title_alter_product_title'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featurecategory',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.category'),
        ),
        migrations.CreateModel(
            name='Awesome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
        ),
    ]
