# Generated by Django 4.0.1 on 2022-01-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeruser',
            name='company',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
