# Generated by Django 4.0.1 on 2022-01-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_order_shipping_address_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('DS', 'Delivered to shipper'), ('C', 'Complete')], max_length=100, null=True),
        ),
    ]
