# Generated by Django 4.0.1 on 2022-01-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_remove_order_is_completed_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_type',
            field=models.CharField(choices=[('PD', 'Payment on delivery'), ('PP', 'Paypal')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('DS', 'Delivered to shipper'), ('C', 'Complete')], max_length=50),
        ),
    ]
