# Generated by Django 4.0.1 on 2022-01-09 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_shippingaddress_phone_number_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.FloatField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to='order.order'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
